name: test updating wiki
on:
    push:
        branches:
            - main
jobs:
  create-wiki-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Check out wiki
        uses: actions/checkout@v3
        with:
          repository: 'sylvain-spryker/test-action-wiki.wiki'
          ref: 'master'
          path: 'test-action-wiki.wiki'
      - name: Update summary.md if needed
        run: |
          cd ./test-action-wiki.wiki && \
          echo "test $(date)" > test.md
          echo "# output internal" >> test.md
          echo "\`\`\`" >> test.md
          cat ../output.out >> test.md && \
          echo "" >> test.md && \
          echo "\`\`\`" >> test.md && \
          git config --global user.email "test@spryker.com" && \
          git config --global user.name "Action test" && \
          git add test.md && \
          git commit -m "Update test.md at $(date)" && \
          git push origin master